//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlassaktWebApi.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Master_Course
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Master_Course()
        {
            this.UnitsOfCourses = new HashSet<UnitsOfCourse>();
        }
    
        public int PK_ID { get; set; }
        public string CourseName { get; set; }
        public Nullable<bool> Active { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UnitsOfCourse> UnitsOfCourses { get; set; }
    }
}
