//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlassaktWebApi.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UnitsOfCourse
    {
        public int PK_ID { get; set; }
        public int UnitID { get; set; }
        public string UnitName { get; set; }
        public Nullable<int> CourseID { get; set; }
        public Nullable<bool> Active { get; set; }
    
        public virtual Master_Course Master_Course { get; set; }
    }
}
