//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KlassaktWebApi.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserDetail
    {
        public int PK_ID { get; set; }
        public string UserID { get; set; }
        public string UserPassWord { get; set; }
        public Nullable<bool> IsActive { get; set; }
    }
}
